application: shopkeep
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "7d"

builtins:
- admin_redirect: on
- datastore_admin: on

handlers:
- url: /js
  static_dir: static/js
  mime_type: application/javascript
- url: /css
  static_dir: static/css
  mime_type: text/css
- url: /images
  static_dir: static/images
  mime_type: text/png
- url: /(search(/(.*))?)?
  script: search.app
- url: /users/(.+)/items/(.+)
  script: item.app
- url: /users/(.+)/items
  script: search.app
- url: /users/(.*)
  script: user.app
- url: /messages/(.+)
  script: message.app
  login: required
  secure: always
- url: /collection/(.+)/(.+)
  script: collection.app
- url: /messages
  script: inbox.app
  login: required
  secure: always
- url: /log(/(.*))?
  script: log.app
  login: required
  secure: always

admin_console:
  pages:
  - name: Audit Log
    url: /log
